name: face_recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.12
  - pip
  # TensorFlow con GPU (conda resolverá CUDA/cuDNN automáticamente)
  - tensorflow-gpu=2.15.0
  # Otras dependencias
  - pillow>=11.2.1,<12.0.0
  - scikit-learn>=1.7.0,<2.0.0
  - dlib>=19.24.0,<20.0.0
  # Paquetes que solo están en PyPI
  - pip:
    - deepface>=0.0.93,<0.0.94
    - tf-keras==2.15.0
    - tensorflow-io-gcs-filesystem==0.31.0