name: face_recognition
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.12
  - pip
  
  
  # TensorFlow (conda-forge incluye GPU automáticamente)
  - tensorflow=2.15.*
  
  # Dependencias básicas
  - numpy
  - opencv
  - pillow>=11.2.1,<12.0.0
  - scikit-learn
  - dlib
  
  # Solo lo que no esté en conda
  - pip:
    - mediapipe>=0.10.0
    - deepface>=0.0.93,<0.0.94
    - tf-keras==2.15.0
    - tensorflow-io-gcs-filesystem==0.31.0